#:import utils kivy.utils

<HomeScreen>:
    FloatLayout:
        canvas:
            Color:
                rgb: utils.get_color_from_hex("39B3F2")
            Rectangle:
                size: self.size
                pos: self.pos
        GridLayout:
            #Put Logo here
            rows: 1
            pos_hint: {"top": 1, "left": 1}
            size_hint: 1, .3
            Image:
                source: "icons/TLKLogo.png"
        Label:
            #Intro text here
            pos_hint: {"top": .8, "left": 1}
            size_hint: 1, .5
            text: "[b]Welcome to TLKNav! Get started below![/b]"
            markup: True
        GridLayout:
            #Add Menu Buttons
            rows: 1
            pos_hint: {"top": .2, "left": 1}
            size_hint: 1, .2
            ImageButton:
                source: "icons/info-icon-light.png"
                on_press:
                    self.source = "icons/info-icon-dark.png"
                on_release:
                    self.source = "icons/info-icon-light.png"
                    app.change_screen("about_screen")
            ImageButton:
                source: "icons/Map-icon-light.png"
                on_press:
                    self.source = "icons/Map-icon-dark.png"
                on_release:
                    self.source = "icons/Map-icon-light.png"
                    app.change_screen("resource_screen")
            ImageButton:
                source: "icons/start-icon-light.png"
                on_press:
                    self.source = "icons/start-icon-dark.png"
                on_release:
                    app.change_screen("program_screen")
                    self.source = "icons/start-icon-light.png"
            
            
