<ProgramScreen>:

    start: start
    end: end
    
    canvas:
        Color:
            rgb: utils.get_color_from_hex("39B3F2")
        Rectangle:
            size: self.size
            pos: self.pos
            
    FloatLayout:
        GridLayout:
            #Put Logo here
            rows: 1
            pos_hint: {"top": 1, "left": 1}
            size_hint: 1, .3
            Image:
                source: "icons/TLKLogo.png"
        TextInput:
            id: start
            multiline:False
            hint_text: "Your current location"
            size_hint: .8, .1
            pos_hint: {"top": .7, "right": .9}
        TextInput:
            id: end
            multiline:False
            hint_text: "Where you want to go"
            size_hint: .8, .1
            pos_hint: {"top": .6, "right": .9}
        Label:
            id: error_message
            text: "Invalid room(s)"
            color: {1,0,0}
            size_hint: 1, .5
            pos_hint: {"top": .4, "right": .9}
        LabelButton:
            canvas.before:
                Color:
                    rgb: utils.get_color_from_hex("#35477d") if self.state == 'normal' else utils.get_color_from_hex("#3244AA")
                Rectangle:
                    size: self.size
                    pos: self.pos
            text: "[b]Search![/b]"
            markup: True
            size_hint: .8, .1
            pos_hint: {"top": .5, "right" :.9}
            on_release:
                root.btn()
        GridLayout:
            #Add Menu Buttons
            rows: 1
            pos_hint: {"top": .2, "left": 1}
            size_hint: 1, .2
            ImageButton:
                source: "icons/info-icon-light.png"
                on_press:
                    self.source = "icons/info-icon-dark.png"
                on_release:
                    self.source = "icons/info-icon-light.png"
                    app.change_screen("about_screen")
            ImageButton:
                source: "icons/Map-icon-light.png"
                on_press:
                    self.source = "icons/Map-icon-dark.png"
                on_release:
                    self.source = "icons/Map-icon-light.png"
                    app.change_screen("resource_screen")
            ImageButton:
                source: "icons/home-icon-light.png"
                on_press:
                    self.source = "icons/home-icon-dark.png"
                on_release:
                    app.change_screen("home_screen")
                    self.source = "icons/home-icon-light.png"
            
    
